CREATE DATABASE PROJETO_ROMAN
GO


USE PROJETO_ROMAN;

--TIPO USUARIO

CREATE TABLE TIPOUSUARIO (
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	tipo VARCHAR(70) UNIQUE NOT NULL
);
GO

--USUARIO

CREATE TABLE USUARIO (
	idUsuario INT PRIMARY KEY IDENTITY,
	idTipoUsuario TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO(idTipoUsuario),
	nome VARCHAR(100) NOT NULL,
	email VARCHAR(256) NOT NULL,
	senha VARCHAR(18) NOT NULL
);
GO

--PROFESSORES

CREATE TABLE PROFESSORES (
	idProfessor INT PRIMARY KEY IDENTITY,
	idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	nomeProfessor VARCHAR(60) NOT NULL
);
GO

--TEMA PROJETOS
CREATE TABLE TEMA (
	idTema INT PRIMARY KEY IDENTITY,
	nomeTema VARCHAR(50)
);
GO

--PROJETOS

CREATE TABLE PROJETOS (
	idProjeto INT PRIMARY KEY IDENTITY,
	idTema INT FOREIGN KEY REFERENCES TEMA(idTema),
	idUsuario INT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	nomeProjeto VARCHAR(60) NOT NULL,
	);
GO

ALTER TABLE PROJETOS 
ADD descricao VARCHAR(200) NOT NULL;



